services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - neighborify-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - neighborify-network

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - neighborify-network

networks:
  neighborify-network:
    driver: bridge

volumes:
  mongodb-data:
